src/main/java/services/ParseCatalog.java

I was receiving error code from this file. After doing some research, I found the error was caused due to my system language is set in Chinese which has different DateTimeFormat. By setting Locale.ENGLISH, this error is gone ; )

Forcing Locale to be English to prevent Error

---

src/main/resources/building.txt

- Shorten the names for building.txt
- Remove Long Island Tandon location since it is closed
=> This makes it easier for users to handle in the front-end side as it will shorten the length of location string

Shorten building.txt names

---

README.md
docs/CONTRIBUTING.md

In README.md's example command, we can't have both year and term flag, so change term to semester to get the spring semester.
In Contributing.md, need to add space before -jar flag so it's not interpreted as "java-jar". Then, change name from "schedge-all.jar" to "schedge.jar"

fix command line errors in readme and contributing files

---

schedge.bat

PR related to #14. Minor issue, but good QOL fix for anyone on Windows.

Change path to .jar file in .bat script

---

src/main/java/cli/templates/LoginMixin.java

when missing --username and --pwd, we should ask for "usrename" and "pwd" instead of time.

fix cli's shop enroll missing parameter instruction

---

src/main/java/database/courses/SelectRows.java

- Section endpoint were throwing exception when passed registration number.
- Just passing an array of integers to the prepared statements instead of just an integer since we are using `Any (?)`

Fixing section endpoints

---

src/main/java/database/instructors/UpdateInstructors.java
src/main/java/scraping/GetRatings.java
src/main/java/scraping/models/Rating.java
src/main/java/utils/Utils.java

Sorry for the delay getting this out; this fixes the breaking issues with RMP scraping but since the Duplicate Instructors issue is still unresolved there are still logging statements in the code and further work to be done.
The main issue was the rating being `null` and throwing an `IllegalArgumentException`; this is resolved by returning `-1.0f` when no rating is found. This way we don't have to worry about passing `null` arguments and we can still check if no rating exists by seeing if it is negative.

Resolve RMP scraping bugs

---

src/main/java/api/App.java
src/main/java/api/v1/CoursesEndpoint.java
src/main/java/api/v1/GenerateScheduleEndpoint.java
src/main/java/api/v1/Health.java
src/main/java/api/v1/SchoolInfoEndpoint.java
src/main/java/api/v1/SearchEndpoint.java
src/main/java/api/v1/SectionEndpoint.java

- Endpoint base class now implements handler
- Replaced some copy-pasted term parsing code with a call into `parseTerm`
- Endpoints now return or throw instead of calling `ctx.json`
- Deleted `SemesterCode`
- New architecture supports computing something before and after each endpoint runs

Refactored Endpoint: reduce nesting, support custom logic

---

src/main/java/api/App.java
src/main/java/api/v1/CampusEndpoint.java
src/main/java/database/models/AugmentedMeeting.java
src/main/java/scraping/PeopleSoftClassSearch.java
src/main/java/utils/Nyu.java
src/main/java/utils/Utils.java

- Adds an endpoint to query the campuses that Schedge is aware of currently
- Refactors the campus code to `Nyu.Campus`
- Adds a bunch of stupid fucking getter methods so that the goddamn OpenApi plugin will actually do its goddamn job

Campus Endpoint, adding various docs as well

---

build.gradle
src/main/java/api/App.java
src/main/resources/api/index.html

Completes #159
- Removes dependency on OpenAPI WebJar crap
- Drops JAR size from `24M` down to `15M`

Use Standard ReDoc index.html instead of webjar

---

build.gradle
src/main/java/actions/ScrapeTerm.java
src/main/java/cli/Database.java
src/main/java/cli/Scrape.java
src/main/java/scraping/PeopleSoftClassSearch.java
src/main/java/scraping/ScrapeSchedge.java

Completes #126
- Switch to using `HttpClient` API from Java 11
- Remove `async-http-client` as a dependency
- Remove `throws` declarations that are redundant
- JAR size is now `12M`, down from `15M`
Second order benefits:
- Scraper can be more easily parallelized, by just creating more clients. Previous client would create a new thread-pool for each new client, which is no bueno.
- Scraper can more easily integrate with Java Loom down the road
- Compiles are faster

Remove Async Http Client as a dependency

---

build.gradle
src/main/java/actions/ScrapeTerm.java
src/main/java/api/v1/CoursesEndpoint.java
src/main/java/api/v1/GenerateScheduleEndpoint.java
src/main/java/api/v1/SchoolInfoEndpoint.java
src/main/java/api/v1/SearchEndpoint.java
src/main/java/cli/Database.java
src/main/java/cli/Mixins.java
src/main/java/cli/Scrape.java
src/main/java/utils/Nyu.java

- Switches `Mixins.Term` to use `fa2020` format
- `schedge db scrape-term` now accepts `fa2020` format as positional parameter
- `schedge db scrape-term` can accept multiple terms
- Move `parseTerm` from endpoint into `Nyu.Term` class

Improve Term CLI

---

src/main/java/actions/ScrapeTerm.java

- Adds a call to `clearPrevious` so that new scrapes don't duplicate data

Clear previous data from term

---

src/build/docker/Dockerfile

- Switch dockerfile base to `eclipse-temurin`
- In the process, using JRE 19 instead of 17, anticipating a transition into using Project Loom

Switch to `eclipse-temurin`

---

src/main/java/actions/CopyTermFromProduction.java
src/main/java/scraping/ScrapeSchedgeV1.java
src/main/java/scraping/ScrapeSchedgeV2.java

Using `V1` and `V2` suffixes to differentiate them

Rename ScrapeSchedge and ScrapeSchedge2

---

.github/workflows/deploy.yml
.github/workflows/scrape.yml
.github/workflows/test.yml
docs/CONTRIBUTING.md
src/main/java/api/App.java
src/main/java/cli/Database.java
src/main/java/cli/Main.java
src/main/java/cli/Mixins.java
src/main/java/cli/Scrape.java
src/main/java/database/GetConnection.java
src/main/java/database/Migrations.java

- Move migration runs to the initializer of `GetConnection.HolderClass`
- Add CI/CD runner for all the tests
- Upgrade Java version to JDK 19
- Term Mixins separated into `TermOptions` and `TermArg`
- Term class converter registered globally instead of on individual systems
- populate allows passing in multiple terms through `@Parameters`

Add Test runs on CI for PR branches and `main`

---

.github/workflows/java-compile.yml
.github/workflows/java-formatting.yml
.github/workflows/java-test.yml
.github/workflows/js-formatting.yml

- Rename checker workflow jobs to start with language name then a dash
- Add "Java - Typecheck"
- Remove `on.pull_request` and remove branch restrictions to `on.push`

Renaming Jobs, adding "Java - Typecheck"

---

src/main/java/scraping/ScrapeSchedgeV1.java

Used the model of
- `UT` -> `Tisch School of Arts`
- `NT -> `Non-Credit Tisch School of Arts`
to fill in `NB`, `NY`, `NI`, etc. etc.
A note, `UI` is one of the names for `NYU Shanghai`

Added placeholder values for schools filled in when doing `ScrapeSchedgeV1`

---

package.json
src/main/java/cli/Database.java
src/main/java/cli/Scrape.java
src/main/java/scraping/ScrapeEvent.java

- Create `ScrapeEvent.cli()` which returns a `Consumer` which outputs to `Logger` and `ProgressBar`
- Remove `yarn ci-test` since tests always run now

Refactor Event handlers for ScrapeEvent

---

.github/workflows/deploy.yml
.github/workflows/java-compile.yml
.github/workflows/java-test.yml
build.gradle
docker-compose.yml

Eclipse temurin doesn't have an image for aarch64, which breaks M1 machines.
Also have to fiddle with some Java versions, for reasons that I do not understand.

Add `platform: linux/amd64` to schedge service in docker compose file

---

src/build/docker/entrypoint.sh
src/main/java/api/App.java
src/main/java/utils/Utils.java

Today I learned that bash is even dumber than I thought.
The `entrypoint.sh` script wasn't using `exec`, so the `SIGTERM` that Docker sends to the container was being eaten by `bash` and then nothing was happening, or potentially `bash` translated the signal to another signal which was then ignored. Not sure, don't really care, this fixes the problem.
Resource: https://vsupalov.com/docker-compose-stop-slow/
Also, a few misc. improvements that were written while debugging this problem:
- Added integer version of `getEnvDefault`
- Added `SCHEDGE_PORT` to override the port with an environment variable

Improve shutdown speed of schedge container

---

build.gradle
src/main/java/api/App.java

Javalin 5.2.0+ allows you to use micrometer for metrics. This PR upgrades to 5.3.0 to allow using micrometer in the future.

Upgrade Javalin

---

.github/workflows/java-test.yml
docs/CONTRIBUTING.md
package.json
src/main/java/cli/Database.java

- `ci-populate` is a bit weird; the tests are run during development too potentially, so might as well make it possible to scrape the test data in development too.
- Changes `compile` to not use `check` since it can be confusing
- Changes the contributing guide to reflect the correct Java version

Switch from `ci-populate` to `test-populate`

---

README.md

I'm not going to engage in an arms race with NYU's IT team. Adding reCAPTCHA to their site is a pretty clear indication that they do not want Schedge to exist. Oh well, we had a good run.

Update README.md with notice about reCAPTCHA

---

README.md

I'm a new student at Tandon and I developed a NYU Course Schedule tool. Here are some of its features:
A better UI interface, making course selection and checking easier.
Access your course information anytime and anywhere, supported on both PC and mobile devices.
Share your course schedule with classmates, friends or relatives.
One-click access to RateMyProfessor.
no ads, login registration or other unnecessary features.
You can try the tool here: https://nyu.myschedule.xyz/#/ Feel free to recommend it to other students or provide any feedback or suggestions.

add  NYU Course Schedule

---

src/build/production/README.md
src/build/production/docker-compose.yml

Adding the environment variable reference back in to the docker compose
also adding more info to the readme

Update prod files
