- kotlin/database/connect.kt
- kotlin/models/api.kt
- kotlin/models/chrono.kt
- kotlin/models/nyu.kt
- kotlin/services/query_service.kt
- kotlin/services/scrape_service.kt
- I added comments to the code to clarify its usage. 
- I added to the Enum class Section Type to the Unknown one. I also added the data class accordingly to what I have found.
> Adding comments and code to SectionType

- src/main/java/scraping/SimpleBatchedFutureEngine.java
I simplified and sped up `SimpleBatchedFutureEngine`. Now, instead of waiting on each future in turn, it first checks all futures to see if any are done, then goes to sleep for a timeout period, and does this repeatedly until a non-null result is found or the input set has been exhausted.
Before this PR, querying the Spring 2020 term took roughly 65 seconds; now it takes 27-32.
Just a sidenote: before asynchrony, it took roughly 600 seconds to query the Spring 2020 term, so we've come a long way. (tested using commit f77c684)
> 2x speedup in scraper

- src/main/java/Main.java
- src/main/java/cli/database.java
- src/main/java/cli/parse.java
- src/main/java/cli/schedge.java
Final piece for java cli to scrape/query/serve from db
> Adding db cli

- src/main/java/cli/Scrape.java
- src/main/java/scraping/models/Section.java
- src/main/java/services/ParseSection.java
- Removing unused functions
- Remove Loc from roomNumber String
> Minor fix with location and cli

- src/main/java/nyu/SubjectCode.java
- src/main/java/scraping/query/QueryCatalog.java
Acad_group for NYU Shanghai is UI but code for subject would be BIOL-SHU. Fixed for data to be scraped
> Fixing bugs with NYU Shanghai data

- src/main/java/nyu/SubjectCode.java
- src/main/java/scraping/query/QueryCatalog.java
Acad_group is UG
Subject code is UGPH-GU
> fix UG public health data not scraped

- src/main/java/cli/Database.java
- src/main/java/cli/Query.java
- src/main/java/scraping/GetRatings.java
- src/main/java/scraping/models/Instructor.java
- src/main/java/scraping/query/QueryCatalog.java
Fix the bug with updating rating for professors
> RMP is finished

- src/main/java/cli/Database.java
- src/main/java/cli/Parse.java
- src/main/java/cli/Query.java
- src/main/java/cli/Schedge.java
- src/main/java/cli/Scrape.java
- src/main/java/cli/Shop.java
- src/main/java/cli/templates/OutputFileMixin.java
- src/main/java/cli/templates/RegistrationNumberMixin.java
- src/main/java/cli/templates/TermMixin.java
Adding help message for each command and subcommand. Users is now suggested with adding --help to see the full options of CLI command/subcommand.
> Documentation

- src/main/java/cli/Database.java
- src/main/java/cli/Query.java
Avoid using abbreviation for RMP. Adding more to the sub-command's description to be more detailed.
> RMP Explanation

- .gitignore
- build.gradle
- Password for DB in gradle build file is "docker" but in GetConneciton.java is empty. Not sure which one to follow but I will go with one in GetConnection.java
> Updating Gradle

- README.md
- docs/CONTRIBUTING.md
- docs/MAC_DEVELOPMENT.md
- src/main/java/database/courses/SelectRows.java
This should fix the latest bug #82
> fixing registration number bugs with left join

- src/pages/course.jsx
- src/pages/course.module.css
- src/pages/index.module.css
- src/pages/schedule.jsx
- src/pages/schedule.module.css
- src/pages/school.jsx
- src/pages/school.module.css
- src/pages/subject.jsx
- src/pages/subject.module.css
A set of refactors to the frontend to transition off of `styled-components`. This has no effect in dev, but reduces the number of weird CSS glitches in prod.
> Frontend refactors

- .gitattributes
- docs/CONTRIBUTING.md
- src/build/docker/Dockerfile
Fixed some nonsense with CRLF I guess. I truly have no idea.
- Added note about JDK version
- Fixed CRLF things I think?
- Added debug line to the DockerFile so this takes less time next time hopefully
> Fixes to enable Windows development

- src/main/java/database/courses/InsertFullCourses.java
- src/main/java/scraping/PeopleSoftClassSearch.java
- src/main/java/utils/ArrayJS.java
- src/main/java/utils/Nyu.java
- Add ArrayJS
- reformat `InsertFullCourses`
- `JsonInclude....` -> `import static` + `NON_NULL`
> Refactors from the scraper

- src/main/java/actions/ScrapeTerm.java
- src/main/java/api/v1/SearchEndpoint.java
- src/main/java/cli/Database.java
- src/main/java/database/courses/InsertFullCourses.java
- src/main/java/database/courses/SearchRows.java
- src/main/java/database/models/FullRow.java
- src/main/java/database/models/Row.java
- src/main/java/scraping/PeopleSoftClassSearch.java
- src/main/java/utils/Nyu.java
- src/main/java/utils/Utils.java
- src/main/migrations/V01__Create_tables.sql
- src/main/migrations/V02__Add_schools_and_subjects.sql
- src/main/migrations/V03__Update_schools_and_subjects.sql
- Removes unused fields from the old database model
- Edits existing migrations because we cannot re-use the old DB
- Adds fake version of `ScrapeTerm` that only scrapes `MATH-UA`, but successfully inserts it into the DB
> Database insertion of scrape result

- build.gradle
- src/main/java/api/v1/GenerateScheduleEndpoint.java
- src/main/java/api/v1/SearchEndpoint.java
- src/main/java/database/courses/SearchRows.java
Separating out the refactors from the Javalin Upgrade PR. This is especially important because I am very confused how to fix this issue I'm having with the upgrade, and need to simplify the migration PR.
- Fix typo "regstration"
- Remove searching for smaller rows because search is getting fucked right now anyways
- Unindented `build.gradle`
> Refactors that slipped into the Javalin Upgrade PR

- src/main/java/api/App.java
Changing some small code style here and there.
> Style changes in api/App.java

- src/main/java/database/models/AugmentedMeeting.java
- src/main/java/utils/Nyu.java
Makes more timestamps timezone-aware. Still doesn't provide the course time zone as part of the output; that should be done later.
> Add timezone awareness to the schedule generator

- src/main/java/actions/ScrapeTerm.java
- src/main/java/cli/Database.java
- src/main/java/cli/Scrape.java
- src/main/java/scraping/PeopleSoftClassSearch.java
- src/main/java/utils/Nyu.java
- Added campuses
- Made term scraping incremental, so that the live object count is lower
- Switched `PeopleSoftClassSearch` to static methods
- 
https://github.com/A1Liu/schedge/issues/162
> Improve Term Scraping again

- src/main/java/api/App.java
- src/main/java/api/v1/ListTermsEndpoint.java
- src/main/java/database/SelectTerms.java
- List terms with data available
> Terms endpoint

- src/main/java/utils/Nyu.java
> Add another campus

- src/main/java/utils/Nyu.java
- Abu Dhabi - Other
- Dominican Republic
- Zambia
- Cuba
- Buenos Aires
- Ireland
- London
> Add another set of campuses

- src/components/Attributes.js
- src/components/Instructor.js
- src/components/util.jsx
- src/pages/course.tsx
- src/pages/subject.tsx
- Ran `yarn format`
- Fix null exception from `splitLocation` not checking and not being typed
> Fix null exception and format some stuff

- build.gradle
- package.json
- src/main/java/api/App.java
- yarn.lock
Got annoyed by the warnings
- Disable linter warning that's not relevant for static hosting
- Update browserlist
- Upgraded dependencies
> Minor development fixes

- src/main/java/database/InsertCourses.java
- src/main/java/database/SelectRows.java
- src/main/java/database/models/Row.java
- src/main/java/scraping/PSCoursesParser.java
- src/main/java/utils/Nyu.java
- src/migrations/V04__Add_section_name.sql
> Missing data in API response

- package.json
- yarn.lock
- `luxon` for Time zone stuffs
- `@svgr/webpack` for `svg` handling
> New Dependencies

- src/main/java/database/SearchRows.java
- src/test/java/test/SearchTest.java
- Fixes #208
- Adds regression test for basic search behavior
- Fixes null pointer exception in `search` when `meetings` is empty
> Fix Search Regression found in #208

- src/main/java/actions/CopyTermFromProduction.java
- src/main/java/cli/Database.java
- src/main/java/cli/Main.java
- src/main/java/database/InsertCourses.java
- src/test/java/test/CoursesTest.java
- Scraping broke in the process of changing to `ZonedDateTime`
- Moved `Main` into `cli`
- Moved logic of `schedge db populate` into its own method for testing
- Added test for this path
> Fix Scraping

- .gitignore
- docs/CONTRIBUTING.md
- Update Contributing guide to include Yarn and NodeJS
- Include the `next` resource folder in version control so that `yarn build` works without silent failures
> Developer Experience Improvements

- package.json
- src/main/java/scraping/PeopleSoftClassSearch.java
- src/test/java/test/ParserTest.java
- src/test/resources/term-sp2022.html.snap
- it broke; this fixes it.
- Adds test case for it as well
> Fix Term parsing of sp2022

- src/main/java/scraping/PeopleSoftClassSearch.java
- Found out about `Objects.requireNonNullElse` today, very cool
> Null Check Fix

- docs/CONTRIBUTING.md
- src/main/java/actions/ScheduleSections.java
- src/main/java/api/v1/GenerateScheduleEndpoint.java
- src/main/java/api/v1/Health.java
- src/main/java/api/v1/ListTermsEndpoint.java
- src/main/java/utils/Nyu.java
- src/test/java/test/ScheduleTest.java
- Add some examples to `Campus`
- Example (empty) data added to `Health` endpoint
- Delete unused constant
- Added some more information to `CONTRIBUTING.md`
- Added another test to check whether the schedule generated by the schedule code has the right number of meetings
> Minor Documentation Changes

- package.json
- src/main/java/api/App.java
- src/main/java/api/v1/Health.java
> Fix Status Endpoint

- .github/workflows/deploy.yml
- .github/workflows/formatting.yml
- .github/workflows/java-formatting.yml
- .github/workflows/java-test.yml
- .github/workflows/js-formatting.yml
- src/main/java/actions/CopyTermFromProduction.java
- src/main/java/api/v1/GenerateScheduleEndpoint.java
- src/main/java/api/v1/Health.java
- src/main/java/cli/Main.java
- src/main/java/cli/Scrape.java
- src/main/java/database/models/AugmentedMeeting.java
- Add Formatting check for JS code
- Add Formatting check for Java code
- Rename Java test job from `build` to `java-test` so it's more easy to use with the required status settings
- Reformat a few files that weren't formatted before
> Formatting checks in CI

- .github/workflows/enable-scraping.yml
- .github/workflows/java-test.yml
Create a job that can be triggered to allow a scrape to happen
> Create Job for Checking Scrape Permissions

- .clang-format
- .github/workflows/java-formatting.yml
- docs/CONTRIBUTING.md
- src/main/java/actions/CopyTermFromProduction.java
- src/main/java/cli/Database.java
- src/main/java/cli/Main.java
- src/main/java/scraping/ScrapeSchedgeV1.java
- src/main/java/scraping/ScrapeSchedgeV2.java
- Rewrite `ScrapeSchedgeV1` to actually do what it should
- Use `ScrapeSchedgeV1` in `db populate`
> Scrape Schedge V1

- README.md
I'm unsure whether the status/waitlistTotal fields are disingenous. Showing this information here is at lesat a start to not being misleading.
> Update README with a limitations section for transparency

- src/main/java/actions/ScrapeTerm.java
- src/main/java/scraping/PSCoursesParser.java
- src/main/java/scraping/PeopleSoftClassSearch.java
- src/main/java/scraping/ScrapeEvent.java
Makes it easier to work with in very specific ways that are relevant in this current moment
> Refactor ScrapeEvent to its own file

- .github/workflows/deploy.yml
- .github/workflows/scrape.yml
- src/main/java/api/App.java
- src/main/java/api/v1/Health.java
- Return build version from health
- Added `source` to scrape job
> Return build version from Health

- .github/workflows/deploy.yml
> Wait for Success in Deploy script

- README.md
Added the front end I wrote to README
> Add new front end to list

- build.gradle
- src/main/java/actions/CopyTermFromProduction.java
- src/main/java/api/App.java
- src/main/java/api/v1/CoursesEndpoint.java
- src/main/java/cli/Database.java
- src/main/java/database/Migrations.java
- src/main/java/database/UpdateSchools.java
- src/main/java/scraping/PSClient.java
- src/main/java/scraping/ScrapeSchedgeV1.java
- src/main/java/scraping/ScrapeSchedgeV2.java
- src/main/java/utils/Nyu.java
- src/main/java/utils/Try.java
- src/main/java/utils/Utils.java
- Change `switch` statements to use the new switch statement expressions where relevant
- Use `record` for `Subject` and `Term`
- Miscellaneous changes to clean up stuff
> Upgrade Java to version 17

- src/main/java/api/App.java
- src/main/java/cli/Database.java
- src/main/java/database/InsertCourses.java
- src/main/java/scraping/ScrapeSchedgeV1.java
- Logger messages in CI are a little noisy so I changed a few `info` to `debug`
- deleted an unnecessary comment
- Removing unnecessary `toString` calls
> Miscellaneous cleanups

- build.gradle
- src/main/java/api/App.java
- Upgrades to Javalin 5.2.0 to get access to the Micrometer plugin
- Adds the Micrometer plugin
- Adds prometheus endpoint at `/api/prometheus`
> Add Micrometer plugin and Prometheus endpoint

- build.gradle
- src/main/java/api/App.java
This reverts commit 25952a279d4c47f8aa88d35284b659c58a4e17fc.
API Docs have stopped working. No idea why. This commit caused.
> Revert "Add Micrometer plugin and Prometheus endpoint (#298)"

- .github/workflows/deploy.yml
- src/main/java/actions/CopyTermFromProduction.java
- src/main/java/scraping/ScrapeSchedgeV2.java
Add an easier way to update the compose file in production, using a special branch
> Production compose system

- .dockerignore
- .github/workflows/java-test.yml
- .gitignore
- build.gradle
- docker-compose.yml
- src/.clang-format
- src/build/Dockerfile
- src/main/java/actions/ScheduleSections.java
- src/main/java/api/v1/CoursesEndpoint.java
- src/main/java/api/v1/ScrapingEndpoint.java
- src/main/java/database/SelectSubjects.java
- src/main/java/scraping/PSClient.java
- src/main/java/utils/Nyu.java
- src/main/java/utils/Utils.java
- src/test/java/test/CoursesTest.java
- Move stuff to `/build` since Spotless doesn't seem to understand outdir, and it's fine to keep the Java standard way I guess :((
- Switch to "switch expressions" now that the formatter understands them
- Added a test for the courses error
> Some refactors

- src/main/java/utils/Nyu.java
- Kenya
- Singapore
- Costa Rica
- IDK what to do for "Other Study Abroad" but it's also there
> added more campuses

- .github/workflows/deploy.yml
> Deploy continuously

- .github/workflows/deploy.yml
> Add deployment concurrency group

- build.gradle
- docs/CONTRIBUTING.md
- src/build/gradle/gradle-wrapper.properties
- src/main/java/api/App.java
- Update Javalin to latest version
- Update Gradle to more recent version
- Update copy on API page to reflect API being more stable
> Update dependencies, copy

- src/main/java/api/App.java
Javalin static files handling is kinda awful
> Fix another `staticFiles` bug

- src/main/java/api/App.java
Getting real tired of this stuff
> Redirect to trailing for `/api`
